"""Convert Template Designer Excel files to NeXus format.

This module provides functionality to convert Excel templates generated by the
Template Designer into NeXus (.nxs) format files. The conversion process:

1. Parses the Excel file using TemplateDesignerParser
2. Extracts the hidden JSON blueprint from the TemplateDesigner sheet
3. Converts data to pyambit data model (Substances, ProtocolApplication)
4. Uses pyambit's nexus_writer to generate NeXus file

Example:
    >>> from pynanomapper.datamodel.templates.excel_to_nexus import excel_to_nexus
    >>> nexus_file = excel_to_nexus("template.xlsx", "output.nxs")
"""

import uuid
from typing import IO, Union
from pathlib import Path
import pyambit.datamodel as mx
from pynanomapper.datamodel.templates.template_parser import TemplateDesignerParser
import nexusformat.nexus as nx


def excel_to_nexus(
    xlsx_file: Union[str, Path, IO],
    output_path: Union[str, Path] = None,
    hierarchy: bool = False
) -> str:
    """
    Convert Template Designer Excel file to NeXus format.
    
    Args:
        xlsx_file: Path to Excel file or file-like object. Must be an Excel file
            generated by Template Designer with a hidden TemplateDesigner sheet
            containing the JSON blueprint.
        output_path: Optional path for output .nxs file. If None, will use
            the same name as input file with .nxs extension.
        hierarchy: If True, organize NeXus entries by protocol category hierarchy.
            Default is False for flat structure.
        
    Returns:
        Path to the generated NeXus file as a string.
        
    Raises:
        ValueError: If Excel file doesn't contain TemplateDesigner sheet
        Exception: If conversion fails
        
    Example:
        >>> # Convert Excel to NeXus
        >>> nexus_path = excel_to_nexus("my_template.xlsx")
        >>> print(f"Created: {nexus_path}")
        
        >>> # Specify output path
        >>> nexus_path = excel_to_nexus("template.xlsx", "output/data.nxs")
        
        >>> # Use hierarchical organization
        >>> nexus_path = excel_to_nexus("template.xlsx", hierarchy=True)
    """
    # Parse Excel file
    parser = TemplateDesignerParser(xlsx_file)
    
    # Convert to Substances with study data
    substances = parser.to_substances()
    
    # Convert to NeXus format
    nx_root = substances.to_nexus(hierarchy=hierarchy)
    
    # Determine output path
    if output_path is None:
        if isinstance(xlsx_file, (str, Path)):
            output_path = Path(xlsx_file).with_suffix('.nxs')
        else:
            output_path = "output.nxs"
    
    output_path = str(output_path)
    
    # Save NeXus file
    nx_root.save(output_path, mode="w")
    
    return output_path


def excel_to_protocol_application(
    xlsx_file: Union[str, Path, IO]
) -> mx.ProtocolApplication:
    """
    Convert Template Designer Excel file to ProtocolApplication object.
    
    This is useful if you want to work with the data model directly
    without generating a NeXus file.
    
    Args:
        xlsx_file: Path to Excel file or file-like object
        
    Returns:
        ProtocolApplication object containing parsed data
        
    Example:
        >>> from pynanomapper.datamodel.templates.excel_to_nexus import excel_to_protocol_application
        >>> pa = excel_to_protocol_application("template.xlsx")
        >>> print(f"Protocol: {pa.protocol.category.code}")
        >>> print(f"Effects: {len(pa.effects)}")
    """
    parser = TemplateDesignerParser(xlsx_file)
    return parser.to_protocol_application()


def excel_to_substances(
    xlsx_file: Union[str, Path, IO]
) -> mx.Substances:
    """
    Convert Template Designer Excel file to Substances object.
    
    Args:
        xlsx_file: Path to Excel file or file-like object
        
    Returns:
        Substances object containing all parsed materials and study data
        
    Example:
        >>> from pynanomapper.datamodel.templates.excel_to_nexus import excel_to_substances
        >>> substances = excel_to_substances("template.xlsx")
        >>> print(f"Number of substances: {len(substances.substance)}")
    """
    parser = TemplateDesignerParser(xlsx_file)
    return parser.to_substances()
